### ISSUE TITLE
Menu button is hardly visible on mobile phones

### ISSUE THREAD

**Issue by wilzbach** [dlang/D-Blog-Theme#24]
I really feel bad for being the only one reporting issues, but the menu button is just a grey box:

![image](https://user-images.githubusercontent.com/4370550/35991580-ea3efbf0-0d07-11e8-863a-5670d0be9344.png)

Here's a CSS quickfix that works for me:

```css
.site-branding .secondary-toggle {
  background-color: grey;
  color: grey;
}
.site-branding .secondary-toggle a.hamburger::after {
    content: "\f0c9";
    font-family: FontAwesome;
    color: white;
    font-size: 30px
    margin-left: -17px;
}
```

![image](https://user-images.githubusercontent.com/4370550/35992227-fbe57ca6-0d09-11e8-9750-8db9140c5a27.png)
